name: Maven Build & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PartyChat
        path: target/*.jar
        
    - name: Deploy to GitHub Packages
      if: github.ref == 'refs/heads/main' || github.event_name == 'release'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Current ref: ${{ github.ref }}"
        echo "Event name: ${{ github.event_name }}"
        mvn --batch-mode deploy
